### PR TITLE
Add feature to match a class when updating or deleting

### PR DESCRIPTION
**Pull request by adelriosantiago**
This allows to `update` / `remove` only an specified class

### CODE REVIEW

**Comment by adelriosantiago** [comment]
BTW is this feature already present in a different way?

I couldn't find a way to remove a particular connection.

**Comment by diamond-msc** [comment]
Hey @adelriosantiago,

thanks for your contribution.

> BTW is this feature already present in a different way?

Can you please take a look at http://jsfiddle.net/0h4Laxq8/.
This example demonstrates how you can remove only the connections for a certain `class`.

Is this what you want?

If so, maybe you could add an example to the README, or a section to the Wiki?

**Comment by adelriosantiago** [comment]
@diamond-msc. I know it is possible to remove all connections but I was looking for a feature that would only remove (or update) only a small set of them.

In the fiddle you provided, how would you delete only the connection from A to B without removing the connection to the top box?

**Comment by diamond-msc** [comment]
Disconnecting a specific connection needs a bit more dedication when setting up the connections:
http://jsfiddle.net/28hkxom4/

Here, we add a special `class` to the connection we want to address later. (for removal)

If I read your change correctly, you also assume the connections have a dedicated `class` for making them a selectable `update` and `remove` target.

I can imagine some APIs for making this task simpler without planning at setup time, but maybe we don't need that for your use case?

**Comment by diamond-msc** [comment]
closing for now

**Pull request closed without merging**
